NYULibraries/spatial_data_repository

config/environments/development.rb, config/environments/test.rb
Handles the following warning in dev/test db environments:
```
DEPRECATION WARNING: Leaving `ActiveRecord::ConnectionAdapters::SQLite3Adapter.represent_boolean_as_integer`
set to false is deprecated. SQLite databases have used 't' and 'f' to serialize
boolean values and must have old data converted to 1 and 0 (its native boolean
serialization) before setting this flag to true. Conversion can be accomplished
by setting up a rake task which runs
ExampleModel.where("boolean_column = 't'").update_all(boolean_column: 1)
ExampleModel.where("boolean_column = 'f'").update_all(boolean_column: 0)
for all models and all boolean columns, after which the flag must be set to
true by adding the following to your application.rb file:
Rails.application.config.active_record.sqlite3.represent_boolean_as_inte …
```
=> deprecate sqllite bool_as_int on dev/test

spec/fixtures/solr_documents/nyu-indexmap.json, spec/fixtures/solr_documents/sunsetpark-lidar-diagonal-fixture.json, spec/fixtures/solr_documents/sunsetpark_lidar_orthog-fixture.json
Hi Andrew, this is to add the correct JSON files for the diagonal and orthogonal flights.
=> Adds metadata for diagonal and orthogonal Sunset Park lidar index maps

lib/nyugeoblacklight/curated_collections.rb, spec/fixtures/solr_documents/laefer-covid-test.json
=> Laefer no modal fixture

.github/workflows/ci.yml, .rubocop.yml, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/catalog_controller.rb, app/controllers/concerns/nyu_slug_concern.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/wms_controller.rb, app/helpers/application_helper.rb, spec/factories/users.rb, spec/features/homepage_spec.rb, spec/features/search_spec.rb, spec/features/show_page_spec.rb, spec/routing/user_routing_spec.rb, spec/spec_helper.rb, spec/support/controller_macros.rb, spec/support/features.rb, spec/support/features/session_helpers.rb
Adding linting to the app to unify coding style and sanitize code base.
=> Add Rubocop

.rubocop.yml, Gemfile, Rakefile, Vagrantfile, app/controllers/application_controller.rb, app/controllers/concerns/nyu_slug_concern.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/models/concerns/multi_download_concern.rb, app/models/concerns/rights_concern.rb, app/models/concerns/wms_rewrite_concern.rb, app/models/search_builder.rb, app/models/solr_document.rb, app/models/user.rb, config.ru, lib/nyugeoblacklight/curated_collections.rb, lib/nyugeoblacklight/multi_direct_downloads.rb, lib/tasks/sdr.rake, spec/features/show_page_spec.rb
We did not have any linting rules set up, so code conformity was non-existent
- configured the `.rubocop.yml` file for ignored directories and Cops (for now).
- verified all Cops are satisfied.
=> linting and rules for green builds

Gemfile, Gemfile.lock, config/schedule.rb, lib/tasks/vacate_searches.rake, spec/factories/search.rb, spec/support/tasks.rb, spec/tasks/vacate_searches_spec.rb, spec/whenever/schedule_spec.rb
We persist `search` objects and need a manner by which to vacate old search data
- write a rake task to vacate searches that are a week old
- use `whenever` to create a scheduled cron job
=> Cron job to clear search

config/schedule.rb
We want the new `cron` job to run at an explicit time as to properly monitor its performance. 
update `whenever` config
=> update cron config

app/controllers/application_controller.rb, spec/routing/user_routing_spec.rb
When users log out, they get redirected to an OAuth landing page, which is jarring.
Add a redirect to the `root_path` to keep eyeballs on the app
https://geo-stage.library.nyu.edu/
=> Add Logout Redirect

app/views/layouts/application.html.erb, config/settings.yml
Missing data stream in google analytics v4
Add gtag script (Closes #273)
Feature
(Might've been easier than I thought since we don't have custom/legacy event tracking...?)
=> add g4a tag

app/components/curated_collections/curated_collection_component.html.erb, app/components/curated_collections/curated_collections_component.html.erb, app/views/layouts/blacklight.html.erb
The `Recently Updated` Feature includes data from collections we do not want to display
Remove `Recenly Updated` widget
=> remove "Recently Updated" and make "Featured Collection" full row

app/views/catalog/_downloads_collapse.html.erb
KMZ-type downloads are not working properly
Remove `kmz` type from `downloads_collapse` component.
=> Filter out KMZ download by type

Gemfile.lock
The most recent PR merge of #323 failed due to a fairly fresh DoS vulnerability in the rexml gem.
Update rexml from 3.3.1 to 3.3.2
Dependencies
=> Updates rexml to address DoS vulnerability

config/environments/production.rb
#310 - Sending records via email (and SMS) fails on Staging and Production due to an SSL issue when trying to connect via SMTP.
Switch ActionMailer from using SMTP (the default) to using sendmail.
bug-fix
=> Switch from SMTP to sendmail for delivering mail

config/environments/production.rb
While testing out the sendmail switch, sending email now generated the following error:
```
ArgumentError (SMTP From address may not be blank: nil)
```
Set a default from email address for ActionMailer: `no-reply@geo.nyu.edu`
bug-fix
=> Setting a default from address for emails

app/controllers/catalog_controller.rb
Addresses #310 
The historical usage of the Email feature does not warrant the effort required to set up an email service currently.
Disable the email tool
Feature
=> Disable email tool for Records

app/controllers/catalog_controller.rb
Addresses #311 
The historical usage of the SMS feature does not warrant the effort required to set up an email service currently.
Disable the SMS tool
Feature
=> Disable SMS tool for Records

public/robots.txt
We have a lot of traffic that is likely caused by crawlers and bots scraping the site.
Use `robots.txt` entries as [suggested by the GeoBlacklight documentation](https://geoblacklight.org/docs/implementation_recommendations/) to cull some of these requests.
Enhancement
=> Add GeoBlacklight suggested robots.txt entries

public/robots.txt
Googlebot keeps requesting URLs like `/catalog/F44DD53A-82DD-4B2B-B0AE-7B9352112DFD/catalog/nyu-2451-34565` which is not a valid request and returns a 404. In the last 24 hours alone there have been 15k requests for URLs like these.
Add an entry to `robots.txt` to Disallow these URL requests from bots.
Addresses #316 
Chore
=> Disallow invalid URL that pattern Googlebot keeps trying to request

Gemfile.lock
There are 2 new DoS vulnerabilities in rexml 3.3.2
Upgrade to 3.3.4
Dependencies
=> Update rexml gem to address DoS vulnerabilities

README.md
For a new developer it's not immediately clear how to successfully run tests in your local development environment, especially since the default Rake task fails.
Add details about running the test suite and individual tests to the README.
Chore
=> Adds details about running tests to the README

.bundler-audit.yml, .github/workflows/ci.yml
Ignored CVE's are managed separately between local development and GitHub Actions
Use bundler audit's configuration file to ignore the same CVE's locally and in GitHub Action
This also adds CVE-2024-6531 which currently does not have a fix but is blocking builds from passing.
Chore
=> Switch to bundler-audit configuration file

.rubocop.yml
After running `sdr-cli clone` in my local development environment I ended up with a large number of directories under `tmp/opengeometadata`. This resulted in Rubocop taking a really long time to run, if it ever finished at all.
Add `tmp` and other Git ignored directories to Rubocop's ignore list.
Chore
=> Add large directories to Rubocop's ignore list

README.md, lib/tasks/sdr.rake
Often we need to test functionality against NYU production data but there's no clear way to load that data.
Create an `sdr:load_nyu_data` Rake task that clones the `edu.nyu` OGM repository and indexes its Aardvark files into Solr
Chore
=> Adds Rake tasks to easily load NYU data locally

config/routes.rb
Requests to `/catalog/opensearch.xml` are generated a 404 error and throwing `Blacklight::Exceptions::RecordNotFound`
Our `config/routes.rb` has deviated from GBL 4.1's and needed to be re-ordered.
Addresses #354 
bug-fix
=> Fix order of GBL /catalog routes

config/routes.rb
Our routes file has an extraneous `/feedback` routes that aren't used for anything.
Remove them!
Addresses #359
Chore
=> Remove unused feedback routes

app/controllers/wms_controller.rb, lib/nyugeoblacklight/wms_layer.rb, spec/lib/nyu_geoblacklight/wms_layer_spec.rb
Restricted records use the NYU proxy to let the front end load maps via the restricted GeoServer. When a user clicks on a feature to identify it, the request goes through the Rails server but the Rails app isn't allowed through the proxy.
Strip the proxy from the WMS URL so that our backend requests go straight to the Restricted GeoServer.
Addresses #369 
bug-fix
=> Strip out proxy from Rails-based WMS requests

app/models/concerns/rights_concern.rb
It may be unclear to folks not on the NYU VPN/Network as to why they can't preview NYU restricted records
Add additional explanation to the alert for restricted records explaining why you might not be able to see the data.
Enhancement
=> Adds clarification when viewing restricted NYU records

app/views/catalog/_laefer_notice.html.erb, spec/features/show_page_spec.rb
Alert message on Dublin LiDAR records have expired links and surveys that are no longer active
Remove expired links and maintain the reference to the YouTube flyover video and the DOI.
chore
=> Remove expired links in Dublin LiDAR record alert

Gemfile, Gemfile.lock
Tiny PR to bump `sdr_cli` version number in Gemfile & Gemfile.lock.
In short, the new `sdr_cli` version updates the `index` command's `--directory` option to more intuitively take a path to a local directory rather than a Glob string matching record paths.
=> bump sdr_cli version, pin to tag

lib/tasks/sdr.rake
Small fix for a very old solr_wrapper issue. See: https://github.com/cbeer/solr_wrapper/issues/69 and https://github.com/NYULibraries/spatial_data_repository/issues/47. Tagged as `chore` bc it only impacts local dev/test instance
=> workaround for core exists error

Gemfile.lock
There are a few CVEs that break the build.
Update the affected gems: net-map, nokogiri and rack
Dependencies
=> Update net-imap, nokogiri and rack due to CVEs

Gemfile.lock
There are currently CVEs for nokogiri and net-imap
Update the gems
dependencies
=> Upgrade Nokogiri and net-imap for CVEs
